### ISSUE TITLE
error with QBCore.Functions.CreateCallback('fx=screen:server:UpdateData')

### ISSUE THREAD

**Issue by kathryn2101** [JericoFX/qb-impound#1]
![image](https://user-images.githubusercontent.com/89110153/146928363-f468d870-d68b-4431-b59b-d732f2da0f9a.png)

**Comment by JericoFX** [comment]
Can you try it now?

**Comment by kathryn2101** [comment]
added in the new stuff so far no errors on restart just logging into the city now will let you know

**Comment by kathryn2101** [comment]
it all works now thank you
