### ISSUE TITLE
Cars go to dept and show in the database as in depot but when i go to depot it says no vehicle in depot

### ISSUE THREAD

**Issue by kathryn2101** [JericoFX/qb-impound#2]
so im doing the impound and it goes through ok and shows in the players_vehicles database that why gone to the depot and how much the depot price as showed in the image

![image](https://user-images.githubusercontent.com/89110153/147355869-411b04ca-f28b-4b2a-b679-2542d7098187.png)

i have also deleted he police impound as it would always send the cars there no idea why

anyway as i was saying i went to the city impound and i get this message even though my car is meant to be here

![image](https://user-images.githubusercontent.com/89110153/147355944-5bc929bf-4ac9-4ab0-8549-96d86ccf7b21.png)

**Comment by JericoFX** [comment]
this script work only with my garages because i simplify the "states"

**Comment by kathryn2101** [comment]
I had your garage but it wasn't working properly for me so I got rid of it and it said the garage wasn't being worked on anymore and was archived so will I get worked on again?

**Comment by kathryn2101** [comment]
ok so i just got both for my test server to make sure they work its again now conflicting with the police impound and it wont let me get on my bike when i pull it out and its also duping the pull out vehicles

i dont get it, it works on my actual server without your garage but it doesnt pick up anyones vehicles when i use your garage its dupes vehicles and wont let me get in or on the vehicle to drive it away and also goes to the police impound before no jobs are set for it and says only police can use it.

any help please

**Comment by kathryn2101** [comment]
[2021-12-28 14-08-07.zip](https://github.com/JericoFX/qb-impound/files/7785026/2021-12-28.14-08-07.zip)

**Comment by kathryn2101** [comment]
had to zip the vid of proof as said it was too big to send

**Comment by JericoFX** [comment]
im working right now, the problem is the states of the vehicles, you need to modify the states.

**Comment by JericoFX** [comment]
> ok so i just got both for my test server to make sure they work its again now conflicting with the police impound and it wont let me get on my bike when i pull it out and its also duping the pull out vehicles
> 
> i dont get it, it works on my actual server without your garage but it doesnt pick up anyones vehicles when i use your garage its dupes vehicles and wont let me get in or on the vehicle to drive it away and also goes to the police impound before no jobs are set for it and says only police can use it.
> 
> any help please

when i get home i will help you, add me on discord JericoFX#3512

**Comment by kathryn2101** [comment]
ok i added you i got the impound working and garage kinda working the only issue i have now if that it wont save mods to a car when i park it in a garage (posting it here as comments are closed in qb-garages)

it doesnt conflict with the police job anymore and goes in the impound fine and comes out the impound fine also parks in a garage fine and the garage ui is fine just wont save any car modifications if i get any

ill leave you to get back to work and talk to you later :) 

thank you
